import{a as I,i as L,S as P}from"./assets/vendor-D0cagnvz.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();const v="47359148-e6bdc7b546b5534c01c17ed5e",w="https://pixabay.com/api/";async function g(e,r=1,n=15){try{return(await I.get(w,{params:{key:v,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:n}})).data}catch(a){throw console.error("Помилка при отриманні зображень:",a),a}}const y=document.getElementById("gallery"),A=document.getElementById("loader");let f=null;function B(){y.innerHTML=""}function d(e){A.hidden=!e}function m(e){document.getElementById("load-more").hidden=!e}function s(e,r,n){L[e]({title:r,message:n})}function h(e){const r=e.map(({webformatURL:n,largeImageURL:a,tags:t,likes:o,views:i,comments:b,downloads:E})=>`
      <a href="${a}" class="gallery-item">
        <img src="${n}" alt="${t}" loading="lazy" />
        <div class="info">
          <p><b>Likes:</b> ${o}</p>
          <p><b>Views:</b> ${i}</p>
          <p><b>Comments:</b> ${b}</p>
          <p><b>Downloads:</b> ${E}</p>
        </div>
      </a>
    `).join("");y.insertAdjacentHTML("beforeend",r),f?f.refresh():f=new P(".gallery a")}const p=document.getElementById("search-form"),S=document.getElementById("load-more");let l=1,c="";const u=15;p.addEventListener("submit",M);S.addEventListener("click",$);async function M(e){if(e.preventDefault(),c=p.elements.query.value.trim(),!c){s("warning","Warning","Please enter a search term.");return}l=1,B(),d(!0),m(!1);try{const r=await g(c,l,u);if(!r||!Array.isArray(r.hits)){s("error","Error","Invalid API response. Please try again.");return}const n=r.hits;if(n.length===0){s("info","Info","Sorry, no images found.");return}h(n),s("success","Success",`Found ${r.totalHits} images.`),r.totalHits>u&&m(!0)}catch{s("error","Error","Failed to load images. Try again later.")}finally{d(!1)}}async function $(){l+=1,d(!0);try{const e=await g(c,l,u);if(!e||!Array.isArray(e.hits)){s("error","Error","Invalid API response. Please try again.");return}const r=e.hits;h(r);const n=Math.ceil(e.totalHits/u);l>=n&&(m(!1),s("info","Info","We're sorry, but you've reached the end of search results.")),H()}catch{s("error","Error","Failed to load images. Try again later.")}finally{d(!1)}}function H(){const{height:e}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
